name: Build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 * * *'
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out repo
      uses: actions/checkout@v4

    # Runs a set of commands using the runners shell
    - name: Run build script
      shell: pwsh
      run: |-
          .\build.ps1
          cat .\README.md
    
    - name: Commit and push if changed
      shell: bash
      run: |-
        git diff
        git config --global user.email "readme-bot@poychang.net"
        git config --global user.name "README-bot"
        git add -A
        git commit -m "Updated content"
        git push
